on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/geocompx/docker:suggests
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Git
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Initialize gh-pages branch"
          branch: gh-pages
          file_pattern: "."

      - name: Ensure gh-pages branch exists
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}.git
          if ! git ls-remote --exit-code --heads origin gh-pages; then
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initialize gh-pages branch"
            git push origin gh-pages
            git checkout main
          fi

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages